name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        tool: [lknpd]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ matrix.tool }}

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.tool }}
        workspaces: ${{ matrix.tool }}

    - name: Lint
      run: cargo clippy

    - name: Tests
      run: cargo test --verbose
